### ISSUE TITLE
how to run this matlab code?

### ISSUE THREAD

**Issue by DavidHan008** [santhosh-kumar/MultiviewAppearanceTracker#1]
how to run this matlab code?

**Comment by DavidHan008** [comment]
Error using SetupCameraNetwork (line 79)
The specified folder, Output Videos, does not exist

**Comment by santhosh-kumar** [comment]
As specified in the instruction, you can download the sample data folder from: https://www.dropbox.com/s/p2sz9wea0gdnzug/data.tar.gz?dl=0

All the required folders are setup there and you should be able to run the application.
